meta:
  name: 'Pusher'
  version: '${plugin.version}'
  author: 'zenmagick.org'
  description: 'Adds pusher support to the site.'

storefront:
  settings:
    zenmagick:
      base:
        events:
          listeners:
            - zenmagick\plugins\pusher\PusherEventPusher
  autoload:
    psr-0:
      Pusher: vendor
